"""Canonical constants.

The values here are the machine-readable form of `/canon/02-data-classes.md` and
`/canon/03-controls.md`. Runtime policy may tighten them; nothing may loosen them, which is why
they live in code rather than in the signed policy bundle.
"""

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Final


class DataClass(str, Enum):
    C0_OPERATIONAL = "C0"
    C1_AGGREGATE = "C1"
    C2_EVENT = "C2"
    C3_TRACE = "C3"
    C4_IDENTIFIED = "C4"
    C5_MEDIA = "C5"
    C6_PROHIBITED = "C6"


class TrustLevel(str, Enum):
    SOFTWARE_BOUND = "software_bound"
    MODULE_ATTESTED = "module_attested"
    HARDWARE_ATTESTED = "hardware_attested"


class Profile(str, Enum):
    L1 = "RTL-L1"
    L2 = "RTL-L2"
    L3 = "RTL-L3"


PROFILE_TRUST: Final[dict[Profile, TrustLevel]] = {
    Profile.L1: TrustLevel.SOFTWARE_BOUND,
    Profile.L2: TrustLevel.MODULE_ATTESTED,
    Profile.L3: TrustLevel.HARDWARE_ATTESTED,
}

# C3/C4/C5 are refused on software_bound regardless of schema, basis or entitlement (D-008 s1).
CLASSES_PERMITTED: Final[dict[TrustLevel, frozenset[DataClass]]] = {
    TrustLevel.SOFTWARE_BOUND: frozenset(
        {DataClass.C0_OPERATIONAL, DataClass.C1_AGGREGATE, DataClass.C2_EVENT}
    ),
    TrustLevel.MODULE_ATTESTED: frozenset(
        {
            DataClass.C0_OPERATIONAL,
            DataClass.C1_AGGREGATE,
            DataClass.C2_EVENT,
            DataClass.C3_TRACE,
            DataClass.C4_IDENTIFIED,
            DataClass.C5_MEDIA,
        }
    ),
    TrustLevel.HARDWARE_ATTESTED: frozenset(
        {
            DataClass.C0_OPERATIONAL,
            DataClass.C1_AGGREGATE,
            DataClass.C2_EVENT,
            DataClass.C3_TRACE,
            DataClass.C4_IDENTIFIED,
            DataClass.C5_MEDIA,
        }
    ),
}

# C6 is never generated by any profile, so it appears in no permitted set.

# Entitlement is checked *after* trust level, never instead of it: an entitlement can enable a
# class the hardware is capable of, and can never enable one the trust level forbids.
ENTITLEMENT_FOR_CLASS: Final[dict[DataClass, str]] = {
    DataClass.C3_TRACE: "c3_traces",
    DataClass.C4_IDENTIFIED: "c4_recognition",
    DataClass.C5_MEDIA: "c5_media",
}

CLASSES_REQUIRING_BASIS: Final[frozenset[DataClass]] = frozenset(
    {DataClass.C2_EVENT, DataClass.C3_TRACE, DataClass.C4_IDENTIFIED, DataClass.C5_MEDIA}
)

VALID_LAWFUL_BASIS: Final[frozenset[str]] = frozenset(
    {
        "notice.public_space",
        "notice.workplace",
        "consent.explicit",
        "legitimate_use.security",
        "legitimate_use.safety",
        "contract.service",
    }
)

# Canonical per-metric k floors. A policy bundle may raise these; a bundle below any of them is
# refused with floor_below_canon (D-008 s3).
CANON_FLOORS: Final[dict[str, int]] = {
    "footfall": 3,
    "passerby": 3,
    "zone_flow": 3,
    "entry_wait": 3,
    "group_composition": 3,
    "repeat_rate": 3,
    "corporate_occupancy": 10,
    "dwell_time": 20,
    "visit_duration": 20,
    "queue_duration": 20,
}

DEFAULT_FLOOR: Final[int] = 3

# The age gate threshold is deliberately four years above the DPDP definition of a minor.
AGE_GATE_THRESHOLD: Final[int] = 22

# Retention ceilings in days for class C3, by profile. L1 does not persist C3 at all.
C3_RETENTION_DAYS: Final[dict[Profile, int]] = {Profile.L1: 0, Profile.L2: 30, Profile.L3: 90}

SPOOL_DAYS: Final[dict[Profile, int]] = {Profile.L1: 7, Profile.L2: 30, Profile.L3: 90}


class Priority(IntEnum):
    """Spool overflow order (F14 R1). Lower ordinal survives longer."""

    SAFETY_SECURITY = 0
    REFRIGERATION = 1
    OPERATIONAL = 2
    AGGREGATE = 3
    HEALTH = 4


# F14 R2: reconnect window, widened per attempt and spread by a device_id-derived jitter.
BACKOFF_MIN_S: Final[float] = 1.0
BACKOFF_MAX_S: Final[float] = 900.0

# D-005: full local session behaviour for 72 h of T2 outage, read-only thereafter.
OFFLINE_FULL_SESSION_HOURS: Final[int] = 72

# D-001 measured pre-flight thresholds, in MB of usable RAM.
ADAPTER_CAP_THRESHOLDS: Final[tuple[tuple[int, int], ...]] = ((3481, 3), (3338, 2))

# F01 R4: pre-flight must finish while the FE is still at the counter.
PREFLIGHT_BUDGET_S: Final[int] = 300

# F01 R5: an installed OS booted inside this window means the host is not dedicated.
HOST_DEDICATION_WINDOW_DAYS: Final[int] = 7

MAX_PAYLOAD_BYTES: Final[int] = 64 * 1024

# F14 R6: beyond this offset the affected windows are marked time_uncertain.
CLOCK_SKEW_TOLERANCE_MS: Final[int] = 300_000

# F19 R2: recommendation caps compose - per action AND site-wide (D-008 s4).
MAX_RECOMMENDATIONS_PER_SITE_PER_DAY: Final[int] = 3
