"""Which domain a record of each class may live in (M10, F16 R1/R3, C9).

A "domain" is a place with properties, not a directory. The properties are what the retention and
erase paths depend on, so they are stated once here and derived from the checked layout rather than
assumed at each call site:

    DATA, SPOOL   LUKS2, and therefore crypto-erasable: destroying the key slots ends the data.
    AUDIT         append-only and deliberately *not* erasable, so the chain outlives the device
                  (F16 R3). Nothing that must be forgettable may be written here.
    VOLATILE      zram/tmpfs. It does not survive a reboot, which is the point on L1, where a
                  trace may exist while a person is in frame and may not exist afterwards.

The consequence worth stating: a class that must be forgettable and a domain that must be permanent
are mutually exclusive, and `check_placement` refuses that pairing rather than trusting a caller to
pick the right path. `ERASABLE_CLASSES` is the set that motivates crypto-erase existing at all.
"""

from __future__ import annotations

from enum import Enum
from typing import Final

from t1.canon import CLASSES_PERMITTED, PROFILE_TRUST, DataClass, Profile
from t1.platform.layout import DiskLayout, Volume


class Domain(str, Enum):
    DATA = "data"
    SPOOL = "spool"
    AUDIT = "audit"
    VOLATILE = "volatile"


VOLUME_FOR_DOMAIN: Final[dict[Domain, Volume | None]] = {
    Domain.DATA: Volume.DATA,
    Domain.SPOOL: Volume.SPOOL,
    Domain.AUDIT: Volume.AUDIT,
    Domain.VOLATILE: None,
}

CRYPTO_ERASABLE: Final[frozenset[Domain]] = frozenset({Domain.DATA, Domain.SPOOL})
PRESERVED_ON_ERASE: Final[frozenset[Domain]] = frozenset({Domain.AUDIT})

# Everything that carries or could carry a person is on the erasable side of the disk.
ERASABLE_CLASSES: Final[frozenset[DataClass]] = frozenset(
    {DataClass.C3_TRACE, DataClass.C4_IDENTIFIED, DataClass.C5_MEDIA}
)

DOMAIN_FOR_CLASS: Final[dict[DataClass, Domain]] = {
    DataClass.C0_OPERATIONAL: Domain.SPOOL,
    DataClass.C1_AGGREGATE: Domain.SPOOL,
    DataClass.C2_EVENT: Domain.SPOOL,
    DataClass.C3_TRACE: Domain.DATA,
    DataClass.C4_IDENTIFIED: Domain.DATA,
    DataClass.C5_MEDIA: Domain.DATA,
}


class PlacementRefusal(str, Enum):
    CLASS_NEVER_STORED = "class_never_stored"
    CLASS_FORBIDDEN_AT_TRUST_LEVEL = "class_forbidden_at_trust_level"
    WRONG_DOMAIN = "wrong_domain"
    DOMAIN_NOT_ENCRYPTED = "domain_not_encrypted"
    DOMAIN_NOT_ERASABLE = "domain_not_erasable"
    DOMAIN_ABSENT = "domain_absent"
    DOMAIN_OFF_T1_DEVICE = "domain_off_t1_device"


REMEDY: Final[dict[PlacementRefusal, str]] = {
    PlacementRefusal.CLASS_NEVER_STORED: "C6 is generated by no profile and stored by none",
    PlacementRefusal.CLASS_FORBIDDEN_AT_TRUST_LEVEL: (
        "raise the trust level (L2/L3 hardware) or stop producing the class"
    ),
    PlacementRefusal.WRONG_DOMAIN: "write the record to the domain its class is assigned",
    PlacementRefusal.DOMAIN_NOT_ENCRYPTED: "re-image with LUKS2 on the data and spool volumes",
    PlacementRefusal.DOMAIN_NOT_ERASABLE: (
        "the audit domain is preserved on decommission; a forgettable class cannot live there"
    ),
    PlacementRefusal.DOMAIN_ABSENT: "the layout has no such volume; re-image to the SPEC layout",
    PlacementRefusal.DOMAIN_OFF_T1_DEVICE: (
        "move the volume onto the T1 device; T1 never writes to the customer's disk (AD-01)"
    ),
}


def check_placement(
    data_class: DataClass,
    domain: Domain,
    profile: Profile,
    layout: DiskLayout | None = None,
) -> PlacementRefusal | None:
    """Refusals only. `None` is the sole statement that the write may proceed.

    `layout` is optional because the class rules hold whatever the disk looks like; when a layout is
    supplied the physical properties the domain claims are checked against it rather than believed.
    """
    if data_class is DataClass.C6_PROHIBITED:
        return PlacementRefusal.CLASS_NEVER_STORED
    if data_class not in CLASSES_PERMITTED[PROFILE_TRUST[profile]]:
        return PlacementRefusal.CLASS_FORBIDDEN_AT_TRUST_LEVEL
    if DOMAIN_FOR_CLASS[data_class] is not domain:
        return PlacementRefusal.WRONG_DOMAIN
    if data_class in ERASABLE_CLASSES and domain not in CRYPTO_ERASABLE:
        return PlacementRefusal.DOMAIN_NOT_ERASABLE
    if layout is not None:
        return _check_volume(domain, layout)
    return None


def _check_volume(domain: Domain, layout: DiskLayout) -> PlacementRefusal | None:
    volume = VOLUME_FOR_DOMAIN[domain]
    if volume is None:
        return None
    partition = layout.partition(volume)
    if partition is None:
        return PlacementRefusal.DOMAIN_ABSENT
    if partition.device != layout.t1_device:
        return PlacementRefusal.DOMAIN_OFF_T1_DEVICE
    if domain in CRYPTO_ERASABLE and not partition.encrypted:
        return PlacementRefusal.DOMAIN_NOT_ENCRYPTED
    return None
